version: 2.1
aliases:
- &setup_remote_docker
    setup_remote_docker:
      version: 18.09.3
      docker_layer_caching: true
- &docker_login
    run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
executors:
  buildpack:
    environment:
      IMAGE_NAME: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      TF_VERSION: 0.12.2
    docker:
      - image: circleci/buildpack-deps
jobs:
  build:
    executor: buildpack
    steps:
    - checkout
    - *setup_remote_docker
    - *docker_login
    - run: docker build --build-arg TF_VERSION=$TF_VERSION -t $IMAGE_NAME .
    - run: docker save -o image.tar $IMAGE_NAME
    - persist_to_workspace:
        root: .
        paths:
          - ./image.tar
  release:
    executor: buildpack
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - *setup_remote_docker
    - *docker_login
    - run: docker load -i /tmp/workspace/image.tar
    - run: docker tag $IMAGE_NAME $IMAGE_NAME:$TF_VERSION
    - run: |-
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$TF_VERSION

workflows:
  version: 2
  builder:
    jobs:
    - build
    - release:
        requires:
          - build
        filters:
          branches:
            only: master
